### ISSUE TITLE
Cached values

### ISSUE THREAD

**Issue by josuesantamaria** [CultureHQ/adequate_serialization#92]
Hey bro, hope you are doing great my friend!

I have a question for you and I will appreciate it a lot if you can help me. I have an endpoint with a query that changes the results according to some filters, the response is something like this:

```
{ id: 1, name: Ping Pong, user_count: 3 }
```

In the render, the user_count is being cached, and when I apply another filter and the user_count is different, it will display the same `3` because of the cache, so I'm not able to get the right value according to the filter.

I think the problem is because the user_count is not part of the model, and because of that, it is taking the cached value and it does not realize the value was changed.

Can you provide some guidance here my friend?

Thanks for your help

**Comment by kddeisz** [comment]
Probably the easiest way to accomplish this is to serialize a different object than an interest or a skill. The reason is, interests and skills both automatically hit the cache when they are being serialized to json (as per this file: https://github.com/CultureHQ/adequate_serialization/blob/master/lib/adequate_serialization/serializable.rb). But if you serialize a different object, then it's not going to do that.

As an example, you could wrap it in a struct and then serialize that, as in:

```ruby
class Tag < TinyStruct.new(:tag)
  delegate :id, :name, :user_count, to: :tag

  def as_json
    { id: id, name: name, user_count: user_count }
  end
end
```

so then you can have

```ruby
render json: { interests: interests.map { Tag.new(_1) }
```

that way nothing hits the cache.
